// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      mochaTest: {
        test: {
          options: {
            reporter: 'spec',
            require: ['coffee-script', 'should']
          },
          src: ['src/dataglue/test/**/*.coffee']
        }
      },
      coverage: {
        options: {
          reporter: 'html-cov',
          require: ['blanket', 'coffee-script', 'should'],
          quiet: true,
          captureFile: 'src/dataglue/test/coverage.html'
        },
        src: ['src/dataglue/test/**/*.coffee']
      }
    });
    grunt.loadNpmTasks('grunt-mocha-test');
    return grunt.registerTask('default', 'mochaTest');
  };

}).call(this);

/*
//@ sourceMappingURL=Gruntfile.map
*/
