// Generated by CoffeeScript 1.6.2
(function() {
  exports.logger_config = {
    level: process.env.OPENSHIFT_DATA_DIR === void 0 ? 'debug' : 'info',
    format: "[{{timestamp}}] <{{title}}> <{{file}}:{{line}}> {{message}}",
    dateformat: "yyyy-mm-dd hh:MM:ss"
  };

  exports.resolveEnvVar = function(envVar) {
    if (envVar === void 0) {
      return void 0;
    }
    if (/^\$/i.test(envVar)) {
      return process.env[envVar.slice(1, envVar.length)];
    }
    return envVar;
  };

}).call(this);

/*
//@ sourceMappingURL=utils.map
*/
