// Generated by CoffeeScript 1.6.2
(function() {
  var logger, moment, _;

  _ = require('lodash');

  moment = require('moment');

  logger = require('tracer').colorConsole(exports.logger_config);

  exports.logger_config = {
    level: process.env.OPENSHIFT_DATA_DIR === void 0 ? 'debug' : 'info',
    format: "[{{timestamp}}] <{{title}}> <{{file}}:{{line}}> {{message}}",
    dateformat: "yyyy-mm-dd hh:MM:ss"
  };

  exports.resolveEnvVar = function(envVar) {
    if (envVar === void 0) {
      return void 0;
    }
    if (/^\$/i.test(envVar)) {
      return process.env[envVar.slice(1, envVar.length)];
    }
    return envVar;
  };

  exports.verifyPropertyExists = function(obj, field) {
    if ((_.has(obj, field)) && (obj[field] !== void 0) && (obj[field] !== '')) {
      return true;
    } else {
      return false;
    }
  };

  exports.generate_mongo_url = function(obj) {
    var mongourl;

    obj.host = exports.resolveEnvVar(obj.host) || '127.0.0.1';
    obj.port = exports.resolveEnvVar(obj.port) || 27017;
    obj.db = exports.resolveEnvVar(obj.db) || 'test';
    mongourl = void 0;
    if ((obj.user && obj.user !== '') && (obj.pass && obj.pass !== '')) {
      mongourl = "mongodb://" + (exports.resolveEnvVar(obj.user)) + ":" + (exports.resolveEnvVar(obj.pass)) + "@" + (exports.resolveEnvVar(obj.host) || '127.0.0.1') + ":" + (exports.resolveEnvVar(obj.port) || '27017') + "/" + (exports.resolveEnvVar(obj.db)) + "?auto_reconnect=true";
    } else {
      mongourl = "mongodb://" + (exports.resolveEnvVar(obj.host) || '127.0.0.1') + ":" + (exports.resolveEnvVar(obj.port) || '27017') + "/" + (exports.resolveEnvVar(obj.db) || 'dataglue') + "?auto_reconnect=true";
    }
    return mongourl;
  };

  exports.isInteger = function(f) {
    return f !== void 0 && typeof f === 'number' && Math.round(f) === f;
  };

  exports.isFloat = function(f) {
    return f !== void 0 && typeof f === 'number' && !exports.isInteger(f);
  };

  exports.setMongoFieldDataType = function(obj) {
    if (_.isDate(obj)) {
      return 'datetime';
    } else if (_.isBoolean(obj)) {
      return 'boolean';
    } else if (_.isArray(obj)) {
      return 'array';
    } else if (_.isObject(obj)) {
      return 'object';
    } else if (_.isString(obj)) {
      return 'varchar';
    } else if (exports.isInteger(obj)) {
      return 'int';
    } else if (exports.isFloat(obj)) {
      return 'float';
    }
  };

  exports.stringify = function(obj) {
    if (_.isString(obj)) {
      return obj;
    } else if (_.isObject(obj)) {
      return JSON.stringify(obj);
    }
    return obj;
  };

  exports.sqlDbTypes = ['mysql', 'postgresql', 'postgre', 'mariadb'];

  exports.noSqlTypes = ['mongo'];

  exports.isUnixOffset = function(theInput) {
    return /[0-9]{13}/.test(theInput);
  };

  exports.isUnixTimestamp = function(theInput) {
    return /[0-9]{10}/.test(theInput) && String(theInput).length === 10;
  };

  exports.parseDateToOffset = function(theDate, opts) {
    var format, isUnixOffset, isUnixTimestamp, pFormat, utc;

    if (opts == null) {
      opts = {};
    }
    format = opts != null ? opts.format : void 0;
    utc = (opts != null ? opts.utc : void 0) || true;
    isUnixOffset = exports.isUnixOffset(theDate);
    isUnixTimestamp = exports.isUnixOffset(theDate);
    pFormat = (function() {
      switch (format) {
        case 'year':
          return 'YYYY';
        case 'month':
          return 'YYYY-MM';
        case 'day':
          return 'YYYY-MM-DD';
        case 'hour':
          return 'YYYY-MM-DD HH';
        default:
          return void 0;
      }
    })();
    if (exports.isUnixOffset(theDate)) {
      if (utc) {
        return +moment.utc(theDate);
      } else {
        return +moment(theDate);
      }
    } else if (exports.isUnixTimestamp(theDate)) {
      return +moment.unix(theDate);
    }
    if (_.isDate(theDate)) {
      return +moment.utc(theDate);
    } else if (format === 'year' && _.isNumber(theDate)) {
      if (utc) {
        return +moment.utc(String(theDate), pFormat);
      } else {
        return +moment(String(theDate), pFormat);
      }
    } else {
      if (utc) {
        return +moment.utc(theDate, pFormat);
      } else {
        return +moment(theDate, pFormat);
      }
    }
  };

  exports.parseX = function(item, opts) {
    var xGroupBy, xType;

    if (opts == null) {
      opts = {};
    }
    xType = opts != null ? opts.xType : void 0;
    xGroupBy = opts != null ? opts.xGroupBy : void 0;
    if (_.contains(['date', 'datetime'], xType)) {
      return exports.parseDateToOffset(item, {
        format: xGroupBy
      });
    }
    return item;
  };

}).call(this);

/*
//@ sourceMappingURL=utils.map
*/
