// Generated by CoffeeScript 1.6.2
(function() {
  var assert, should, utils;

  utils = require('../utilitis/utils');

  assert = require('assert');

  should = require('should');

  describe('utils', function() {
    describe('#stringify', function() {
      it('should return a string for a string', function() {
        return utils.stringify('Hello World!').should.equal('Hello World!');
      });
      return it('should return a string for an object', function() {
        return utils.stringify({
          a: 1
        }).should.equal('{"a":1}');
      });
    });
    describe('#isInteger', function() {
      it('should return true for 1', function() {
        return utils.isInteger(1).should.equal(true);
      });
      it('should return true for 1.0', function() {
        return utils.isInteger(1.0).should.equal(true);
      });
      it('should return false for 1.1', function() {
        return utils.isInteger(1.1).should.equal(false);
      });
      return it('should return false for undefined', function() {
        return utils.isInteger(void 0).should.equal(false);
      });
    });
    describe('#isFloat', function() {
      it('should return false for 1', function() {
        return utils.isFloat(1).should.equal(false);
      });
      it('should return false for 1.0', function() {
        return utils.isFloat(1.0).should.equal(false);
      });
      it('should return true for 1.1', function() {
        return utils.isFloat(1.1).should.equal(true);
      });
      return it('should return false for undefined', function() {
        return utils.isFloat(void 0).should.equal(false);
      });
    });
    describe('#resolveEnvVar', function() {
      return it('undefined should return undefined', function() {
        return should.not.exist(utils.resolveEnvVar());
      });
    });
    return describe('#parseDateToOffset ', function() {
      it('parse 2009 with year format', function() {
        return utils.parseDateToOffset('2009', 'year').should.equal(1230786000000);
      });
      return it('parse 2009 with no format', function() {
        return utils.parseDateToOffset('2009', void 0).should.equal(1230786000000);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=testUtils.map
*/
